# from utils import cmdline
# from . import template
# import os

# # write list output for a habit group
# def group_list(out, skill, indent_level):
#     if isinstance(skill,template.Skill):
#         out.write(cmdline.indent(indent_level) + "{}:".format(skill.name) + cmdline.paragraph)
#         indent_level += 1
#     for h in skill.habits:
#         out.write(cmdline.indent(indent_level) + "{}".format(h.name) + cmdline.paragraph)
#     for c in skill.children.values():
#         group_list(out, c, indent_level)


# # write all currently tracked habits to an output file
# def list(path):
#     tp = template.get_template(os.getcwd())
#     with open(path, "w") as f:
#         f.write("GENERATED BY LOGGERTOOL\n")
#         f.write("==================================================" + cmdline.paragraph)
#         group_list(f, tp.daily_habits, 0)

#     print("Wrote new list file at {}".format(path))